---
deploymentSpec:
  flask:
    imageName: rekhanagyalakurthi/pre-interview
    tag: 1.0.7
    replicaCount: 2
    ingress:
      enable: true
      path: /
    ports:
      web:
        type: ClusterIP
        service: 80
        pod: 5000
        nodeport: 31727
    livenessProbe:
      enable: false
    readinessProbe:
      enable: false