name: Prepare-app CI

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches: master

jobs:
  prepare-app:
    name: Build/Publish Image
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the prepare-app action
      - name: Run script action
        run: ./pre-interview.sh --action prepare-app
        env:
          registry_user: ${{ secrets.REGISTRY_USER }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}